### ISSUE TITLE
Add some margins around the Eyevinn Technology logo

### ISSUE THREAD

**Issue by birme** [Eyevinn/android-player#10]

**Comment by ReprogramAkash** [comment]
I would like to work on this.

**Comment by birme** [comment]
Hi! No problem, please do

**Comment by Naveed1891** [comment]
Hi, I would like to work on this project.

**Comment by ReprogramAkash** [comment]
Hi, please review the PR -> https://github.com/Eyevinn/android-player/pull/11 for this issue. Thanks!
